config/routes.rb
Rails.application.routes.draw do
  root   'welcome#home'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/job/:id', to: 'jobs#details', as: :job
  get    '/apply/:id', to: 'jobs#edit', as: :apply
  get    '/company', to: 'companies#show'
  post   '/company', to: 'companies#create'
  delete '/company/:id', to: 'companies#destroy', as: :delete_company


  resource :users, only: [:create]
  resource :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs
  has_many :users
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  has_many :applications
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :company, optional: true
  has_many :applications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def show
    @new_company = Company.new
    @companies = Company.all
  end

  def create
     params = company_params
     company = Company.new(params)
     company.save
     redirect_to company_path
  end

  def destroy
    company = Company.find_by(id: params[:id])
    if company
      company.destroy
    end
    redirect_to company_path
  end

  private

  def company_params
    params.require(:company).permit(:name, :domain)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def show
    if current_user_applicant?
      user_id = current_user.id
      job_applied = Application.where(user_id: user_id).map { |a| a.job_id }
      @jobs = Job.where.not(id: job_applied)
      @companies = get_companies(@jobs)
    elsif current_user_employer?
      company_id = current_user.company_id
      @jobs = Job.where(company_id: company_id)
      @companies = get_companies(@jobs)
    else
      @jobs = Job.all
      @companies = get_companies(@jobs)
    end
  end

  def new
    if not logged_in?
      redirect_to root_path
    else
      @job = Job.new
    end
  end

  def create
    if current_user_employer?
      job_params = get_create_params
      job_params[:company_id] = current_user.company_id
      job = Job.new(job_params)
      if job.save
        @jobs = Job.all
        @companies = get_companies(@jobs)
        render "show"
      else
        render "new"
      end
    end
  end

  def details
    id = get_detail_params[:id]
    @job = Job.find(id)
    if @job
      user_ids = Application.where(job_id: @job.id).map {|a| a.user_id}
      @users = User.find(user_ids.to_a)
    end
  end

  def edit
    if current_user_applicant?
      id = get_detail_params[:id]
      application = Application.new(user_id: current_user.id, job_id: id)
      application.save
    end
    redirect_to jobs_path
  end

  private

  def get_create_params
    params.require(:job).permit(:title, :description)
  end

  def get_detail_params
    params.permit(:id)
  end

  def get_companies(jobs)
    companies_ids = jobs.map{ |j| j.company_id }.to_set.to_a
    Company.find(companies_ids).map{ |c| [c.id, c] }.to_h
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to jobs_path
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = get_params
    email = user_params[:email].strip
    domain = email.split("@").last
    company = Company.find_by(domain: domain)
    if company.nil?
      user_params[:privilege] = "applicant"
      @user = User.new(user_params)
    else
      user_params[:privilege] = "employer"
      user_params[:company_id] = company.id
      @user = User.new(user_params)
    end
    if @user.save
      log_in(@user)
      redirect_to jobs_path
    else
      render "new"
    end
  end

  private

  def get_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def signup
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user_applicant?
    if current_user and current_user.privilege == 'applicant'
      return true
    end
    return false
  end

  def current_user_employer?
    if current_user and current_user.privilege == 'employer'
      return true
    end
    return false
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/show.html.erb
<div class="container">
<h1>Companies</h1>
<%= form_for(:company, url: company_path) do |c| %>
  <div class="form-group">
    <%= c.label :name %>
    <%= c.text_field :name, class: "form-control", placeholder: "Name" %>
  </div>
  <div class="form-group">
    <%= c.label :domain %>
    <%= c.text_field :domain, class: "form-control", placeholder: "Domain" %>
  </div>
  <%= c.submit "Create", class: "btn btn-primary" %>
<% end %>
<hr class="my-4">
<div class="list-group">
  <% @companies.each do |company| %>
    <div class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= company.name %></h5>
        <%= link_to "Delete", delete_company_path(company), method: :delete, class: "btn btn-danger" %>
      </div>
      <p class="mb-1">Company domain: <b><%= company.domain %></b></p>
    </div>
  <% end %>
</div>
</div>

app/views/jobs/details.html.erb
<div class="container">
<h1>Jobs Details</h1>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @job.title %></h5>
    <p class="card-text"><%= @job.description %></p>
  </div>
  <ul class="list-group list-group-flush">
    <% if not @users.nil? and @users.length > 0 %>
      <% @users.each do |user| %>
        <li class="list-group-item"><%= user.name %></li>
      <% end %>
    <% else %>
      <li class="list-group-item">Noboy has apply yet</li>
    <% end %>
  </ul>
</div>
</div>

app/views/jobs/new.html.erb
<div class="container">
<h1>New Job</h1>
<%= form_for(@job) do |j| %>
  <div class="form-group">
    <%= j.label :title %>
    <%= j.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <%= j.label :description %>
    <%= j.text_area :description, class: "form-control", placeholder: "Description" %>
  </div>
  <%= j.submit "Create job", class: "btn btn-primary" %>
<% end %>
</div>

app/views/jobs/show.html.erb
<div class="container">
<h1>Jobs</h1>
<% if current_user_employer? %>
  <%= link_to "Create a job", new_jobs_path, class: "btn btn-success" %>
<% end %>
<div class="list-group">
  <% @jobs.each do |job| %>
    <div class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= job.title %></h5>
        <% if current_user_applicant? %>
          <%= link_to "Apply", apply_path(job), class: "btn btn-primary" %>
        <% end %>
        <% if current_user_employer? %>
          <%= link_to "See applicants", job_path(job), class: "btn btn-primary" %>
        <% end %>
      </div>
      <p class="mb-1"><%= job.description %></p>
      <small><%= @companies[job.company_id].name %></small>
    </div>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fountain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark justify-content-end">
        <% if logged_in? %>
          <span class="navbar-brand"><%= current_user.name %></span>
          <%= link_to "Log out", logout_path, method: :delete, class: "btn btn-light mr-sm-2" %>
        <% else %>
          <%= link_to "Log in", login_path, class: "btn btn-light mr-sm-2" %>
        <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign up</h1>
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "Password confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation" %>
    </div>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/welcome/home.html.erb
<div class="container">
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Fountain</h1>
      <p class="lead">This is the engineering assingment for fountain.</p>
      <hr class="my-4">
      <% if logged_in? %>
        <%= link_to "Jobs", jobs_path, class: "btn btn-primary btn-lg" %>
      <% else %>
          <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-lg" %>
      <% end %>
    </div>
  </div>
</div>